use_frameworks!

platform :ios, 8.0

target 'OC-Category_Example' do
  pod 'OC-Category', :path => '../'

  target 'OC-Category_Tests' do
    inherit! :search_paths

    pod 'Specta'
  pod 'Expecta'
  pod 'FBSnapshotTestCase'
  pod 'Expecta+Snapshots'
  end
end
