//
//  Foundation.h
//  Categories
//
//  Created by 余洪江 on 16/03/01.
//  Copyright © MRJ. All rights reserved.
//

#ifndef Foundation_h
#define Foundation_h

#import "NSArray+Block.h"
#import "NSArray+SafeAccess.h"
#import "NSBundle+AppIcon.h"
#import "NSData+APNSToken.h"
#import "NSData+Base64.h"
#import "NSData+DataCache.h"
#import "NSData+Encrypt.h"
#import "NSData+Gzip.h"
#import "NSData+Hash.h"
//#import "NSData+zlib.h"
#import "NSDate+CupertinoYankee.h"
#import "NSDate+Extension.h"
#import "NSDate+Formatter.h"
#import "NSDate+InternetDateTime.h"
#import "NSDate+Reporting.h"
#import "NSDate+Utilities.h"
#import "NSDateFormatter+Make.h"
#import "NSDecimalNumber+CalculatingByString.h"
#import "NSDecimalNumber+Extensions.h"
#import "NSDictionary+Block.h"
#import "NSDictionary+JSONString.h"
#import "NSDictionary+Merge.h"
#import "NSDictionary+SafeAccess.h"
#import "NSDictionary+URL.h"
#import "NSDictionary+XML.h"
#import "NSException+Trace.h"
#import "NSFileHandle+ReadLine.h"
#import "NSFileManager+Paths.h"
#import "NSHTTPCookieStorage+FreezeDry.h"
#import "NSIndexPath+Offset.h"
#import "NSInvocation+Bb.h"
#import "NSInvocation+Block.h"
#import "NSMutableURLRequest+Upload.h"
#import "NSNotificationCenter+MainThread.h"
#import "NSNumber+CGFloat.h"
#import "NSNumber+RomanNumerals.h"
#import "NSNumber+Round.h"
#import "NSObject+AddProperty.h"
#import "NSObject+AppInfo.h"
#import "NSObject+AssociatedObject.h"
#import "NSObject+AutoCoding.h"
#import "NSObject+Blocks.h"
#import "NSObject+BlockTimer.h"
#import "NSObject+EasyCopy.h"
#import "NSObject+GCD.h"
#import "NSObject+KVOBlocks.h"
#import "NSObject+Reflection.h"
#import "NSObject+Runtime.h"
#import "NSRunLoop+PerformBlock.h"
#import "NSSet+Block.h"
#import "NSString+Base64.h"
#import "NSString+Contains.h"
#import "NSString+DictionaryValue.h"
#import "NSString+Emoji.h"
#import "NSString+Encrypt.h"
#import "NSString+Hash.h"
#import "NSString+Matcher.h"
#import "NSString+MIME.h"
#import "NSString+NormalRegex.h"
#import "NSString+Pinyin.h"
#import "NSString+RemoveEmoji.h"
#import "NSString+Score.h"
#import "NSString+Size.h"
#import "NSString+Trims.h"
#import "NSString+URLEncode.h"
#import "NSString+UUID.h"
#import "NSString+XMLDictionary.h"
#import "NSTimer+Addition.h"
#import "NSTimer+Blocks.h"
#import "NSURL+Param.h"
#import "NSURL+QueryDictionary.h"
#import "NSURLConnection+SelfSigned.h"
#import "NSURLRequest+ParamsFromDictionary.h"
#import "NSUserDefaults+iCloudSync.h"
#import "NSUserDefaults+SafeAccess.h"

#endif /* Foundation_h */
